version: '3.0'

services:
  grafana:
    container_name: 'nullify-grafana-datasource'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/nullify-grafana-datasource
      - ./provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana # Holds grafana state - caches database content (not API keys) between version changes

volumes:
  grafana-storage:
